### ISSUE TITLE
ImageNet training

### ISSUE THREAD

**Issue by sungnyun** [OPTML-Group/DP4TL#1]
Hi, thank you for providing the code for this great work!

I'm right now trying to train the surrogate model by imagenet_train_from_scratch.py, while I also found out there is also adv_imagenet_train_from_scratch.py. What is this file for and how is it different from the former file?

Thanks,

**Comment by NormalUhr** [comment]
Hi, thanks for your interest in our work. You can use the file adv_imagenet_train_from_scratch.py to launch adversarial training. The former is for normal training (minimizing the ERM loss).

**Comment by sungnyun** [comment]
Got it, thanks!
