### ISSUE TITLE
Dear authors, can you kindly reshare the preprocessed data link as it seems expired?

### ISSUE THREAD

**Issue by ldpbuaa** [OPTML-Group/DP4TL#2]
Dear authors, can you kindly reshare the preprocessed data link for Google Drive, as it seems expired?

**Comment by ldpbuaa** [comment]
I managed to create the dataset using FFCV. Thanks for sharing the code!

**Comment by successhaha** [comment]
Hello, I have also encountered the same problem of the link being unavailable. How did you finally resolve the issue?
